#!/bin/bash
# github.com/sudb92/tamildailycalendar
# bash script to view datecalendar at www.mahacalendar.com
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
if [[ "$(stat -c '%z' /tmp/today.jpg 2> /dev/null | cut -d' ' -f1)" -eq "$(date +%Y-%m-%d)" ]]; then
    #echo "Not downloading anew"
    echo ""
else
    #download quietly (-q) to /tmp/today.jpg. -O overwrites, just in case
    wget -q -O /tmp/today.jpg https://www.tamildailycalendar.com/$(date +%Y)/$(date +%-d%m%Y).jpg;
fi

#personal favorite, borderless feh
feh -x -F /tmp/today.jpg

#generic imagefile opener
#xdg-open /tmp/today.jpg &
